services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=blogdb 
      - POSTGRES_USER=myuser 
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: blogdb
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A BlogApp worker --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

volumes:
  db_data:
    driver: local