version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery
  db:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - "5432:5432"
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
