services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart : always
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
