from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from blog.views import PostViewSet 
from rest_framework.authtoken.views import ObtainAuthToken

# Create a router for managing URL patterns
router = DefaultRouter()
router.register(r'posts', PostViewSet)  # Register the PostViewSet with the router

urlpatterns = [
    # Include the URLs generated by the router for the 'posts' endpoint
    path('', include(router.urls)),
    # URL pattern for the Django admin interface
    path('admin/', admin.site.urls),
    # URL pattern for obtaining authentication tokens
    path('api-token-auth/', ObtainAuthToken.as_view(), name='api_token_auth'),
]
